# Copyright 2024 enzoames. All Rights Reserved.

rolesTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ${self:custom.rolesTableName}
    AttributeDefinitions:
      - AttributeName: roleId
        AttributeType: S
      - AttributeName: userId
        AttributeType: S
      - AttributeName: endDate
        AttributeType: S
    GlobalSecondaryIndexes:
      - IndexName: GSI1--roleId-endDate
        KeySchema:
          - AttributeName: roleId
            KeyType: HASH
          - AttributeName: endDate
            KeyType: RANGE
        Projection:
          ProjectionType: ALL
    KeySchema:
      - AttributeName: roleId
        KeyType: HASH
      - AttributeName: userId
        KeyType: RANGE
    BillingMode: PAY_PER_REQUEST
