# Copyright 2024 enzoames. All Rights Reserved.

service: rtmanager-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  profile: rt # from aws creds
  stage: ${opt:stage, 'qa'}
  logs:
    httpApi: true
  iam:
    role: apiLambdaRole
  environment:
    ROLES_TABLE: ${self:custom.rolesTableName}

custom:
  baseName: ${self:service}-${self:provider.stage}
  apiLambdaRoleName: ${self:custom.baseName}-apiLambdaRole
  rolesTableName: rtmanager-db-${self:provider.stage}-roles # name taken from resources/db
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: false
    packager: 'npm'

functions:
  auditLogs:
    handler: functions/auditLogs.handler
    events:
      - httpApi:
          method: post
          path: /rt/auditlogs
  roles:
    handler: functions/roles.handler
    events:
      - httpApi:
          method: get
          path: /rt/roles/{roleId}/expired

resources:
  Description: Resources related to the API Service
  Resources:
    apiLambdaRole: ${file(resources/role.yml):apiLambdaRole}

plugins:
  - serverless-webpack
