# Copyright 2024 enzoames. All Rights Reserved.

service: rtmanager-db

provider:
  name: aws
  runtime: nodejs20.x
  profile: rt # from aws creds
  stage: ${opt:stage, 'qa'}

custom:
  rolesTableName: ${self:service}-${self:provider.stage}-roles
  teachableTableName: teachable-db-${self:provider.stage}-users

resources:
  Description: Resources related to the DB Service
  Resources:
    rolesTable: ${file(resources/dynamodb.yml):rolesTable}
    teachableTable: ${file(resources/teachableDynamodbTable.yml):teachableTable}
